jasypt:
  encryptor:
    password: arkhyterima

example:
  property: "COVID19BACKEND"
spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/Covid19DB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: 
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

jwt:
  clientId: mitrais-care
  client-secret:  mitrais-secret
  accessTokenValidititySeconds: 28800
  refreshTokenValiditySeconds: 288000

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: tomcat
